apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        image: gcr.io/google-samples/hello-app:2.0
        env:
        - name: APP_NAME
          value: "Hello from the environment app name: GUESTBOOK-UI"
        - name: ENV_NAME
          value: "This is demo app"
